[workspace]
title = "cppxx"
version = "v0.1.0"
author = "aufam"
compiler = "c++"
standard = 23

[workspace.vars]
gtest_version = "${gtest_version:-1.17.0}"
nlohmann_json_version = "${nlohmann_json_version:-3.12.0}"
marzer_toml_version = "${marzer_toml_version:-3.4.0}"


[project.debug]
flags = ["-g", "-fsanitize=address,undefined"]
link_flags = ["-fsanitize=address,undefined"]


[project.release]
flags = ["-O3", "-DNDEBUG"]


[project.crypto]
link_flags = ["-lssl", "-lcrypto"]


[project.preprocessor]
git.url = "boostorg/preprocessor"
git.tag = "boost-1.88.0"
include_dirs = ["include/"]


[project.fmt]
git.url = "fmtlib/fmt"
git.tag = "11.2.0"
include_dirs = ["include/"]
flags = ["-DFMT_HEADER_ONLY=1"]


[project.cxxopts]
git.url = "jarro2783/cxxopts"
git.tag = "v3.3.1"
include_dirs = ["include/"]


[project.toml]
sources = ["https://raw.githubusercontent.com/marzer/tomlplusplus/v3.4.0/toml.hpp"]


[project.json]
sources = ["https://github.com/nlohmann/json/releases/download/v${nlohmann_json_version}/json.hpp"]


[project.googletest]
archive = "https://github.com/google/googletest/releases/download/v${gtest_version}/googletest-${gtest_version}.tar.gz"
sources = ["googletest-${gtest_version}/googletest/src/gtest-all.cc", "googletest-${gtest_version}/googletest/src/gtest_main.cc"]

[project.googletest.include_dirs]
public = ["googletest-${gtest_version}/googletest/include/"]
private = ["googletest-${gtest_version}/googletest/"]


[project.core]
sources = ["src/*.cpp"]
flags = ["-Wall", "-Wextra", "-fmacro-prefix-map=${PWD}=cppxx"]
include_dirs = ["include/"]
depends_on = ["preprocessor", "fmt", "json", "toml", "crypto"]


[project.core_debug]
depends_on = ["core", "debug"]


[project.core_release]
depends_on = ["core", "release"]


[project.cppxx]
type = "executable"
sources = ["cmd/*.cpp"]
depends_on = ["core_${build_type:-release}", "cxxopts"]


[project.test]
type = "executable"
sources = ["tests/*.cpp"]
depends_on = ["core_debug", "googletest"]
